### ISSUE TITLE
JSON API compatibility?

### ISSUE THREAD

**Issue by andrewpros** [hummatli/AndroidAppUpdater#10]
Hi.

I'm using json api (http://jsonapi.org/) on my server, is there a possibility the library could support it? Without it i would need to brake the standard to return correct json, and that probably won't be allowed.

Or even better, maybe we could have another init overload with ability to provide our own ProgramInfo callback method, this way i could get it in json api format (it is already there, but different format than ProgramInfo) on my own and then just convert the response to ProgramInfo object, so there would be no need to change much.

And i see it can be done with simple change, the most important part is in the Updater, it is using HttpTools to grab the json, now we just need to provide an callback function in init method and if it is set, call it in Updater instead of requestProgramInfo.

This not only allows us to use any existing update data format from server by simply converting it to ProgramInfo, but also gives the ability to use any method and lib or existing global configuration for requesting that data, even hardcoding some values.

And the best part, no need to change anything in ProgramInfo.

**Comment by hummatli** [comment]
Hi, @andrewpros . Sorry for late answer.

I understood what you mean. Great idea. 

I agree with you. It would be nice if lib supports global rules (JSON API).

If you have time can you help? 

1) Fork project
2) Do it on your fork.
3) Test it as needed 
4) Then create pull request to main repo, "beta" branch
5) Then I will accept it and merge it muster
6) I will you mention you for new functionality on Readme [(contributor list)](https://github.com/hummatli/MAHAndroidUpdater#contributors) and new Release.  
 
By the way you will be contributor of the Lib. :)  You will do your job on own application and contribute for lib. 

But we need to do so that don't disturb users old version. As you said, it will be another overloaded method of "init()" method.

What do you thing?!  Can we do?!

We can discuss further if there is another need.

Regards, Sattar Hummatli

**Comment by andrewpros** [comment]
@hummatli 

Well as a matter of fact i can help, I've already done this changes to integrate it for my own project, so i will make a PR, just give me some time.

**Comment by hummatli** [comment]
Ok @andrewpros. 

Great.

Let me know when you are ready.

**Comment by andrewpros** [comment]
Closed as of https://github.com/hummatli/MAHAndroidUpdater/pull/12
